#!/usr/bin/env python3
"""Generate TypeScript error-message maps from schemas/common/error-codes.yaml.

The SSOT carries a Chinese ``userMessage``, an ``i18nKey`` and a ``retryable``
flag per error code, but until now no codegen consumed it: meeting-web
hand-copied the map (a drift source) and ai-worker-web showed raw codes to
operators. This script emits one ``error-messages.gen.ts`` per frontend so
both consume the contract directly.

Usage:
    python3 scripts/generate-error-messages.py [--output <file>]...

With no arguments, writes to the default committed locations for
meeting-web and ai-worker-web. With ``--output``, writes each given file
(used by the drift check to generate into a temp dir).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

CONTRACTS_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = CONTRACTS_DIR.parent.parent
SOURCE = CONTRACTS_DIR / "schemas" / "common" / "error-codes.yaml"

DEFAULT_TARGETS = [
    PROJECT_ROOT / "apps" / "meeting-web" / "src" / "shared" / "api" / "error-messages.gen.ts",
    PROJECT_ROOT / "apps" / "ai-worker-web" / "src" / "shared" / "api" / "error-messages.gen.ts",
]

HEADER = """\
// AUTO-GENERATED by meeting-contracts/scripts/generate-error-messages.py
// from schemas/common/error-codes.yaml — DO NOT EDIT.
// Regenerate with: npm run codegen (in packages/meeting-contracts)

export interface ErrorCodeInfo {
  /** Operator/user-facing Chinese message from the contract SSOT. */
  userMessage: string;
  /** Whether the failing operation is worth retrying. */
  retryable: boolean;
  /** Stable i18n resource key for future localisation. */
  i18nKey: string;
}

"""

FOOTER = """\

/** Contract userMessage for a code; falls back to the raw code so unknown
 * codes stay visible instead of silently disappearing. */
export function errorCodeMessage(code: string): string {
  return ERROR_CODE_INFO[code]?.userMessage ?? code;
}

export function isErrorCodeRetryable(code: string): boolean {
  return ERROR_CODE_INFO[code]?.retryable ?? false;
}
"""


def ts_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(codes: list[dict]) -> str:
    lines = [HEADER, "export const ERROR_CODE_INFO: Record<string, ErrorCodeInfo> = {\n"]
    for entry in codes:
        code = entry["code"]
        user_message = entry.get("userMessage") or code
        retryable = bool(entry.get("retryable", False))
        i18n_key = entry.get("i18nKey") or f"errors.{code}"
        lines.append(
            f"  {code}: {{ userMessage: {ts_string(user_message)}, "
            f"retryable: {str(retryable).lower()}, i18nKey: {ts_string(i18n_key)} }},\n"
        )
    lines.append("};\n")
    lines.append(FOOTER)
    return "".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", action="append", type=Path, default=None)
    args = parser.parse_args()

    with SOURCE.open(encoding="utf-8") as fh:
        doc = yaml.safe_load(fh)
    codes = doc.get("errorCodes")
    if not isinstance(codes, list) or not codes:
        print(f"FAIL: no errorCodes found in {SOURCE}", file=sys.stderr)
        return 1
    seen: set[str] = set()
    for entry in codes:
        code = entry.get("code")
        if not code:
            print("FAIL: errorCodes entry without a code", file=sys.stderr)
            return 1
        if code in seen:
            print(f"FAIL: duplicate error code {code}", file=sys.stderr)
            return 1
        seen.add(code)

    content = render(codes)
    targets = args.output if args.output else DEFAULT_TARGETS
    for target in targets:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        print(f"  wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
