// AUTO-GENERATED by meeting-contracts/scripts/generate-error-messages.py
// from schemas/common/error-codes.yaml — DO NOT EDIT.
// Regenerate with: npm run codegen (in packages/meeting-contracts)

export interface ErrorCodeInfo {
  /** Operator/user-facing Chinese message from the contract SSOT. */
  userMessage: string;
  /** Whether the failing operation is worth retrying. */
  retryable: boolean;
  /** Stable i18n resource key for future localisation. */
  i18nKey: string;
}

export const ERROR_CODE_INFO: Record<string, ErrorCodeInfo> = {
  AUTH_REQUIRED: { userMessage: "请先登录", retryable: false, i18nKey: "errors.AUTH_REQUIRED" },
  REFRESH_TOKEN_INVALID: { userMessage: "刷新令牌无效或已过期", retryable: false, i18nKey: "errors.REFRESH_TOKEN_INVALID" },
  CSRF_TOKEN_INVALID: { userMessage: "CSRF令牌验证失败", retryable: false, i18nKey: "errors.CSRF_TOKEN_INVALID" },
  PERMISSION_DENIED: { userMessage: "没有执行该操作的权限", retryable: false, i18nKey: "errors.PERMISSION_DENIED" },
  TENANT_CONTEXT_MISSING: { userMessage: "租户上下文缺失", retryable: false, i18nKey: "errors.TENANT_CONTEXT_MISSING" },
  VALIDATION_FAILED: { userMessage: "请求参数不符合要求", retryable: false, i18nKey: "errors.VALIDATION_FAILED" },
  VERSION_CONFLICT: { userMessage: "内容已被更新，请刷新后重试", retryable: false, i18nKey: "errors.VERSION_CONFLICT" },
  IDEMPOTENCY_CONFLICT: { userMessage: "幂等键已被不同请求使用", retryable: false, i18nKey: "errors.IDEMPOTENCY_CONFLICT" },
  TASK_NOT_FOUND: { userMessage: "任务不存在", retryable: false, i18nKey: "errors.TASK_NOT_FOUND" },
  MEETING_NOT_FOUND: { userMessage: "会议不存在", retryable: false, i18nKey: "errors.MEETING_NOT_FOUND" },
  TASK_ATTEMPT_CONFLICT: { userMessage: "任务尝试次数已变化", retryable: false, i18nKey: "errors.TASK_ATTEMPT_CONFLICT" },
  TASK_LEASE_CONFLICT: { userMessage: "任务租约已变化", retryable: false, i18nKey: "errors.TASK_LEASE_CONFLICT" },
  WORKER_LEASE_EXPIRED: { userMessage: "Worker 租约已过期", retryable: true, i18nKey: "errors.WORKER_LEASE_EXPIRED" },
  TASK_RETRY_EXHAUSTED: { userMessage: "任务重试次数已耗尽", retryable: false, i18nKey: "errors.TASK_RETRY_EXHAUSTED" },
  INVALID_TASK_MESSAGE: { userMessage: "任务消息不符合处理要求", retryable: false, i18nKey: "errors.INVALID_TASK_MESSAGE" },
  OSS_OBJECT_NOT_FOUND: { userMessage: "存储对象不存在", retryable: false, i18nKey: "errors.OSS_OBJECT_NOT_FOUND" },
  OSS_READ_FAILED: { userMessage: "存储读取失败", retryable: true, i18nKey: "errors.OSS_READ_FAILED" },
  OSS_WRITE_FAILED: { userMessage: "存储写入失败", retryable: true, i18nKey: "errors.OSS_WRITE_FAILED" },
  UPLOAD_SESSION_EXPIRED: { userMessage: "上传会话已过期", retryable: false, i18nKey: "errors.UPLOAD_SESSION_EXPIRED" },
  UPLOAD_ALREADY_ABORTED: { userMessage: "上传会话已取消", retryable: false, i18nKey: "errors.UPLOAD_ALREADY_ABORTED" },
  UPLOAD_ALREADY_COMPLETED: { userMessage: "上传已完成", retryable: false, i18nKey: "errors.UPLOAD_ALREADY_COMPLETED" },
  UPLOAD_PART_HASH_MISMATCH: { userMessage: "分片校验失败", retryable: false, i18nKey: "errors.UPLOAD_PART_HASH_MISMATCH" },
  UPLOAD_FILE_HASH_MISMATCH: { userMessage: "文件校验失败", retryable: false, i18nKey: "errors.UPLOAD_FILE_HASH_MISMATCH" },
  UPLOAD_FILE_SIZE_MISMATCH: { userMessage: "文件大小不一致", retryable: false, i18nKey: "errors.UPLOAD_FILE_SIZE_MISMATCH" },
  UPLOAD_TOO_MANY_PARTS: { userMessage: "上传分片数量超过上限", retryable: false, i18nKey: "errors.UPLOAD_TOO_MANY_PARTS" },
  UPLOAD_INCOMPLETE_PARTS: { userMessage: "上传分片不完整", retryable: false, i18nKey: "errors.UPLOAD_INCOMPLETE_PARTS" },
  AUDIO_UNSUPPORTED_FORMAT: { userMessage: "音频格式不支持", retryable: false, i18nKey: "errors.AUDIO_UNSUPPORTED_FORMAT" },
  AUDIO_TOO_LONG: { userMessage: "音频超过 4 小时上限", retryable: false, i18nKey: "errors.AUDIO_TOO_LONG" },
  AUDIO_CORRUPTED: { userMessage: "音频文件损坏或无法读取", retryable: false, i18nKey: "errors.AUDIO_CORRUPTED" },
  AUDIO_QUALITY_LOW: { userMessage: "音频质量过低", retryable: false, i18nKey: "errors.AUDIO_QUALITY_LOW" },
  CHANNEL_MAP_FAILED: { userMessage: "声道识别失败", retryable: true, i18nKey: "errors.CHANNEL_MAP_FAILED" },
  ASR_RUNTIME_ERROR: { userMessage: "ASR 推理异常", retryable: true, i18nKey: "errors.ASR_RUNTIME_ERROR" },
  ASR_MODEL_TIMEOUT: { userMessage: "ASR 模型推理超时", retryable: true, i18nKey: "errors.ASR_MODEL_TIMEOUT" },
  ASR_GPU_OOM: { userMessage: "ASR GPU 显存不足", retryable: true, i18nKey: "errors.ASR_GPU_OOM" },
  DIARIZATION_FAILED: { userMessage: "说话人分离失败", retryable: true, i18nKey: "errors.DIARIZATION_FAILED" },
  ALIGNMENT_FAILED: { userMessage: "时间戳对齐失败", retryable: true, i18nKey: "errors.ALIGNMENT_FAILED" },
  SPEAKER_EMBEDDING_FAILED: { userMessage: "声纹特征提取失败", retryable: true, i18nKey: "errors.SPEAKER_EMBEDDING_FAILED" },
  SPEAKER_MATCH_FAILED: { userMessage: "声纹匹配失败", retryable: true, i18nKey: "errors.SPEAKER_MATCH_FAILED" },
  TRANSCRIPT_MERGE_FAILED: { userMessage: "转录合并失败", retryable: true, i18nKey: "errors.TRANSCRIPT_MERGE_FAILED" },
  CALLBACK_AUTH_FAILED: { userMessage: "Worker 回调鉴权失败", retryable: false, i18nKey: "errors.CALLBACK_AUTH_FAILED" },
  CALLBACK_IDEMPOTENCY_CONFLICT: { userMessage: "Worker 回调幂等键冲突", retryable: false, i18nKey: "errors.CALLBACK_IDEMPOTENCY_CONFLICT" },
  WRITEBACK_FAILED: { userMessage: "Worker 回写失败", retryable: true, i18nKey: "errors.WRITEBACK_FAILED" },
  LLM_PROVIDER_TIMEOUT: { userMessage: "LLM 服务超时", retryable: true, i18nKey: "errors.LLM_PROVIDER_TIMEOUT" },
  LLM_SCHEMA_INVALID: { userMessage: "LLM 输出格式不符合要求", retryable: true, i18nKey: "errors.LLM_SCHEMA_INVALID" },
  LLM_EVIDENCE_INVALID: { userMessage: "LLM 输出依据校验失败", retryable: true, i18nKey: "errors.LLM_EVIDENCE_INVALID" },
  LLM_RATE_LIMIT: { userMessage: "LLM 服务限流", retryable: true, i18nKey: "errors.LLM_RATE_LIMIT" },
  LLM_OUTPUT_TRUNCATED: { userMessage: "LLM 输出被截断", retryable: true, i18nKey: "errors.LLM_OUTPUT_TRUNCATED" },
  LLM_DATA_BOUNDARY_BLOCKED: { userMessage: "数据边界策略阻断", retryable: false, i18nKey: "errors.LLM_DATA_BOUNDARY_BLOCKED" },
  RAG_INDEX_FAILED: { userMessage: "RAG 入库失败", retryable: true, i18nKey: "errors.RAG_INDEX_FAILED" },
  VECTOR_SEARCH_FAILED: { userMessage: "向量检索失败", retryable: true, i18nKey: "errors.VECTOR_SEARCH_FAILED" },
  RERANK_UNAVAILABLE: { userMessage: "Rerank 服务不可用，已尝试降级", retryable: true, i18nKey: "errors.RERANK_UNAVAILABLE" },
  RERANK_CONTRACT_ERROR: { userMessage: "Rerank 内部契约或签名配置错误", retryable: false, i18nKey: "errors.RERANK_CONTRACT_ERROR" },
  RAG_RATE_LIMITED: { userMessage: "请求过于频繁，请稍后再试", retryable: true, i18nKey: "errors.RAG_RATE_LIMITED" },
  EXPORT_FAILED: { userMessage: "导出失败", retryable: true, i18nKey: "errors.EXPORT_FAILED" },
  EXPORT_RENDER_FAILED: { userMessage: "导出渲染失败", retryable: true, i18nKey: "errors.EXPORT_RENDER_FAILED" },
  EXPORT_LINK_REVOKED: { userMessage: "导出链接已被撤销", retryable: false, i18nKey: "errors.EXPORT_LINK_REVOKED" },
  EXPORT_CONTENT_STALE: { userMessage: "导出依赖的内容已变更，请先重新生成纪要后重试", retryable: false, i18nKey: "errors.EXPORT_CONTENT_STALE" },
  EXPORT_FORMAT_UNSUPPORTED: { userMessage: "不支持的导出格式", retryable: false, i18nKey: "errors.EXPORT_FORMAT_UNSUPPORTED" },
  EXPORT_ALREADY_FINISHED: { userMessage: "导出任务已结束，无法取消", retryable: false, i18nKey: "errors.EXPORT_ALREADY_FINISHED" },
  OUTBOX_PUBLISH_FAILED: { userMessage: "事件发布失败", retryable: true, i18nKey: "errors.OUTBOX_PUBLISH_FAILED" },
  STALE_REBUILD_VERSION_MISMATCH: { userMessage: "重建完成时上游版本已变化", retryable: false, i18nKey: "errors.STALE_REBUILD_VERSION_MISMATCH" },
  KMS_KEY_UNAVAILABLE: { userMessage: "声纹加密密钥不可用", retryable: true, i18nKey: "errors.KMS_KEY_UNAVAILABLE" },
  LEGAL_HOLD_BLOCKED: { userMessage: "对象处于法定保全状态，不能删除", retryable: false, i18nKey: "errors.LEGAL_HOLD_BLOCKED" },
  LEGAL_HOLD_NOT_FOUND: { userMessage: "法定保全不存在", retryable: false, i18nKey: "errors.LEGAL_HOLD_NOT_FOUND" },
  LEGAL_HOLD_ALREADY_RELEASED: { userMessage: "法定保全已被释放", retryable: false, i18nKey: "errors.LEGAL_HOLD_ALREADY_RELEASED" },
  DELETION_JOB_BLOCKED_BY_LEGAL_HOLD: { userMessage: "删除任务被法定保全阻断", retryable: false, i18nKey: "errors.DELETION_JOB_BLOCKED_BY_LEGAL_HOLD" },
  DELETION_JOB_ALREADY_FINISHED: { userMessage: "删除任务已结束", retryable: false, i18nKey: "errors.DELETION_JOB_ALREADY_FINISHED" },
  BREAK_GLASS_REQUEST_EXPIRED: { userMessage: "紧急访问申请已过期", retryable: false, i18nKey: "errors.BREAK_GLASS_REQUEST_EXPIRED" },
  BREAK_GLASS_INSUFFICIENT_APPROVERS: { userMessage: "紧急访问审批人数不足", retryable: false, i18nKey: "errors.BREAK_GLASS_INSUFFICIENT_APPROVERS" },
  BREAK_GLASS_SELF_APPROVAL_FORBIDDEN: { userMessage: "申请人不能审批自己的紧急访问申请", retryable: false, i18nKey: "errors.BREAK_GLASS_SELF_APPROVAL_FORBIDDEN" },
  AUDIT_QUERY_TOO_BROAD: { userMessage: "审计查询时间窗超出 90 天上限", retryable: false, i18nKey: "errors.AUDIT_QUERY_TOO_BROAD" },
  DOCUMENT_PARSE_FAILED: { userMessage: "文档解析失败", retryable: true, i18nKey: "errors.DOCUMENT_PARSE_FAILED" },
  DOCUMENT_OCR_UNSUPPORTED: { userMessage: "不支持扫描 PDF 或图片 OCR", retryable: false, i18nKey: "errors.DOCUMENT_OCR_UNSUPPORTED" },
  DOCUMENT_TYPE_UNSUPPORTED: { userMessage: "文档类型不支持", retryable: false, i18nKey: "errors.DOCUMENT_TYPE_UNSUPPORTED" },
  DEPENDENCY_UNAVAILABLE: { userMessage: "依赖服务暂不可用", retryable: true, i18nKey: "errors.DEPENDENCY_UNAVAILABLE" },
  INTERNAL_ERROR: { userMessage: "服务内部错误", retryable: false, i18nKey: "errors.INTERNAL_ERROR" },
  INVALID_TASK_PHASE: { userMessage: "任务当前阶段不允许该操作", retryable: false, i18nKey: "errors.INVALID_TASK_PHASE" },
  SPEAKER_REFERENCE_UNAVAILABLE: { userMessage: "声纹参考向量暂不可用", retryable: true, i18nKey: "errors.SPEAKER_REFERENCE_UNAVAILABLE" },
  SPEAKER_REFERENCE_STALE: { userMessage: "声纹参考向量已过期，请重新录入", retryable: false, i18nKey: "errors.SPEAKER_REFERENCE_STALE" },
  PERSON_NOT_FOUND: { userMessage: "人员不存在", retryable: false, i18nKey: "errors.PERSON_NOT_FOUND" },
  PERSON_DISPLAY_NAME_REQUIRED: { userMessage: "请填写姓名", retryable: false, i18nKey: "errors.PERSON_DISPLAY_NAME_REQUIRED" },
  PERSON_DUPLICATE: { userMessage: "已存在同名人员", retryable: false, i18nKey: "errors.PERSON_DUPLICATE" },
  ENROLLMENT_SESSION_NOT_FOUND: { userMessage: "声纹会话已失效，请重新开始", retryable: false, i18nKey: "errors.ENROLLMENT_SESSION_NOT_FOUND" },
  ENROLLMENT_PERSON_MISMATCH: { userMessage: "声纹会话人员不匹配", retryable: false, i18nKey: "errors.ENROLLMENT_PERSON_MISMATCH" },
  ENROLLMENT_NOT_PREVIEWED: { userMessage: "请先预览声纹后再确认", retryable: false, i18nKey: "errors.ENROLLMENT_NOT_PREVIEWED" },
  ENROLLMENT_AUDIO_MISSING: { userMessage: "声纹音频缺失", retryable: false, i18nKey: "errors.ENROLLMENT_AUDIO_MISSING" },
  ENROLLMENT_PERSON_REQUIRED: { userMessage: "请选择人员", retryable: false, i18nKey: "errors.ENROLLMENT_PERSON_REQUIRED" },
  FILE_UPLOAD_NOT_FOUND: { userMessage: "上传会话不存在或已过期", retryable: false, i18nKey: "errors.FILE_UPLOAD_NOT_FOUND" },
  FILE_MIME_NOT_ALLOWED: { userMessage: "不支持该文件类型", retryable: false, i18nKey: "errors.FILE_MIME_NOT_ALLOWED" },
};

/** Contract userMessage for a code; falls back to the raw code so unknown
 * codes stay visible instead of silently disappearing. */
export function errorCodeMessage(code: string): string {
  return ERROR_CODE_INFO[code]?.userMessage ?? code;
}

export function isErrorCodeRetryable(code: string): boolean {
  return ERROR_CODE_INFO[code]?.retryable ?? false;
}
