// ── API Types (Contract-Derived) ────────────────────────────────────
// Re-exported from types.gen.ts (auto-generated by openapi-typescript).
// Enum values and DTO shapes are verified by types-consistency.test.ts.
// To regenerate: npm run codegen:ts

import type { components, operations } from "./types.gen";

// ── API Response Envelope ──────────────────────────────────────────
export type ApiResponse<T = unknown> = Omit<components["schemas"]["ApiResponse"], "data"> & { data: T };
export type ApiError = components["schemas"]["ErrorInfo"];

// ── Pagination ──────────────────────────────────────────────────────
export type PageInfo = components["schemas"]["PageInfo"];
export interface Page<T> {
  items: T[];
  page: PageInfo;
}

// ── Auth ────────────────────────────────────────────────────────────
export type AuthUser = components["schemas"]["AuthUser"];

// ── Meeting ──────────────────────────────────────────────────────────
export type SecurityLevel = components["schemas"]["SecurityLevel"];
export type MeetingStatus = components["schemas"]["MeetingStatus"];
export type Meeting = components["schemas"]["Meeting"];
export type CreateMeetingRequest = components["schemas"]["CreateMeetingRequest"];

// ── Audio Upload ─────────────────────────────────────────────────
export type AudioUploadStatus = components["schemas"]["AudioUploadStatus"];
export type AudioUploadSession = components["schemas"]["AudioUploadSession"];
export type AudioUploadPart = components["schemas"]["AudioUploadPart"];
export type CreateAudioUploadRequest = components["schemas"]["CreateAudioUploadRequest"];
export type CreateAudioUploadPartRequest = components["schemas"]["CreateAudioUploadPartRequest"];
export type CompleteAudioUploadRequest = components["schemas"]["CompleteAudioUploadRequest"];

// ── Task ────────────────────────────────────────────────────────────
export type ProcessingTaskStatus = components["schemas"]["ProcessingTaskStatus"];
export type ProcessingTaskPhase = components["schemas"]["ProcessingTaskPhase"];
export type ProcessingStep = components["schemas"]["ProcessingStep"];
export type ProcessingStepUpdateSource = components["schemas"]["ProcessingStepUpdateSource"];
export type StepStatus = components["schemas"]["StepStatus"];
export type ProcessingTask = components["schemas"]["ProcessingTask"];
export type ProcessingTaskStep = components["schemas"]["ProcessingTaskStep"];
export type TaskStep = ProcessingTaskStep;
export type TaskEvent = components["schemas"]["TaskEvent"];

// ── Transcript (inline data from TranscriptResponse) ──────────────
export type TranscriptSegment = components["schemas"]["TranscriptSegment"];
export type TranscriptData = operations["getTranscript"]["responses"][200]["content"]["application/json"]["data"];

// ── Minutes (inline data from MinutesResponse) ─────────────────────
export type MinutesData = NonNullable<operations["getMinutes"]["responses"][200]["content"]["application/json"]["data"]>;
export type MinutesSection = NonNullable<MinutesData["sections"]>[number];
export type MinutesItem = NonNullable<MinutesSection["items"]>[number];
export type Evidence = NonNullable<MinutesItem["evidence"]>[number];

// ── Speakers ─────────────────────────────────────────────────────────
export type MeetingSpeaker = components["schemas"]["MeetingSpeaker"];

// ── RAG (inline data from RagAnswerResponse) ────────────────────────
export type RagAnswerCoverage = components["schemas"]["RagAnswerCoverage"];
export type RagAnswerDTO = components["schemas"]["RagAnswerDTO"];
export type RagQueryRequest = components["schemas"]["RagQueryRequest"];
export type RagQueryResponse = NonNullable<operations["queryRag"]["responses"][200]["content"]["application/json"]["data"]>;
export type MeetingSegmentCitation = components["schemas"]["MeetingSegmentCitation"];
export type DocumentChunkCitation = components["schemas"]["DocumentChunkCitation"];

// ── Documents ───────────────────────────────────────────────────────
export type Document = components["schemas"]["Document"];
export type CreateDocumentRequest = components["schemas"]["CreateDocumentRequest"];
