// ── API Types (Contract-Derived) ────────────────────────────────────
// Re-exported from types.gen.ts (auto-generated by openapi-typescript).
// Enum values and DTO shapes are verified by types-consistency.test.ts.
// To regenerate: npm run codegen:ts
export {};
