package com.meeting.api.client.common;

public enum ErrorCode {
    AUTH_REQUIRED,
    PERMISSION_DENIED,
    TENANT_CONTEXT_MISSING,
    VALIDATION_FAILED,
    VERSION_CONFLICT,
    IDEMPOTENCY_CONFLICT,
    TASK_NOT_FOUND,
    TASK_ATTEMPT_CONFLICT,
    TASK_LEASE_CONFLICT,
    SECURITY_LEVEL_BLOCKED,
    INTERNAL_ERROR
}
